//! Non-ProXDR source synthesis.
//!
//! Photos with Apple Photographic Styles need the styles scaffold, and the
//! scaffold is generated by the conversion pipeline — which expects a standard
//! container (grid + tiles + Exif + `tmap` + gain grid). ProXDR inputs already
//! are one; anything else has to be rebuilt into one.
//!
//! This module decodes any supported input (HEIC/HEIF via heif-oxide, JPEG via
//! jpeg-decoder, PNG via the png crate) **in Rust** and synthesizes that
//! container with an identity gain map, so no platform codec is involved and
//! every platform behaves identically.
//!
//! Orientation: heif-oxide returns display-oriented pixels (it applies both
//! `irot` and the Exif orientation), matching what a platform codec hands back.
//! The carried-forward Exif is therefore normalized to `Orientation = 1`, or a
//! viewer would rotate a second time. JPEG is decoded unrotated by
//! jpeg-decoder, so its Exif orientation is applied to the pixels here.

use crate::container::ExtractedLhdr;
use crate::{exif, styles_attach, uhdr_jpeg};

/// Decode any supported image to tightly packed 8-bit RGB.
///
/// `oriented` reports whether the decoder already applied the source
/// orientation (HEIC does, JPEG does not).
pub fn decode_to_rgb(data: &[u8]) -> Result<(Vec<u8>, u32, u32, bool), String> {
    if data.starts_with(&[0xFF, 0xD8]) {
        let (rgb, w, h) = crate::jpeg_decode::decode_jpeg_to_rgb(data)
            .map_err(|e| format!("JPEG decode failed: {e}"))?;
        return Ok((rgb, w, h, false));
    }
    if data.starts_with(&[0x89, b'P', b'N', b'G']) {
        let (rgb, w, h) = decode_png(data)?;
        return Ok((rgb, w, h, true));
    }
    // HEIF/HEIC (and anything else heif-oxide can make sense of).
    let image =
        heif_oxide::decode_bytes(data).map_err(|e| format!("HEIF decode failed: {e:?}"))?;
    let (rgb, w, h) = heif_pixels_to_rgb8(&image)?;
    Ok((rgb, w, h, true))
}

/// HEIF pixels are 8- or 10/12-bit, with or without alpha. The pipeline stores
/// 8-bit Main-profile tiles, so 16-bit samples are truncated to their high byte
/// (the same reduction a platform codec performs when asked for 8-bit RGBA).
fn heif_pixels_to_rgb8(image: &heif_oxide::DecodedImage) -> Result<(Vec<u8>, u32, u32), String> {
    let (w, h) = (image.width, image.height);
    if w == 0 || h == 0 {
        return Err("decoded image has zero extent".into());
    }
    let rgb = match &image.pixels {
        heif_oxide::Pixels::Rgb8(v) => v.clone(),
        heif_oxide::Pixels::Rgba8(v) => v
            .chunks_exact(4)
            .flat_map(|p| p[..3].iter().copied())
            .collect(),
        heif_oxide::Pixels::Rgb16(v) => v
            .chunks_exact(3)
            .flat_map(|p| p.iter().map(|&s| (s >> 8) as u8))
            .collect(),
        heif_oxide::Pixels::Rgba16(v) => v
            .chunks_exact(4)
            .flat_map(|p| p[..3].iter().map(|&s| (s >> 8) as u8))
            .collect(),
    };
    let expected = (w as usize) * (h as usize) * 3;
    if rgb.len() < expected {
        return Err(format!(
            "decoded {}x{} RGB is short: {} < {}",
            w,
            h,
            rgb.len(),
            expected
        ));
    }
    Ok((rgb[..expected].to_vec(), w, h))
}

fn decode_png(data: &[u8]) -> Result<(Vec<u8>, u32, u32), String> {
    let mut decoder = png::Decoder::new(std::io::Cursor::new(data));
    decoder.set_transformations(png::Transformations::EXPAND | png::Transformations::STRIP_16);
    let mut reader = decoder.read_info().map_err(|e| format!("PNG header: {e}"))?;
    let mut buf = vec![0u8; reader.output_buffer_size()];
    let info = reader
        .next_frame(&mut buf)
        .map_err(|e| format!("PNG decode: {e}"))?;
    let (w, h) = (info.width, info.height);
    let channels = match info.color_type {
        png::ColorType::Rgb => 3,
        png::ColorType::Rgba => 4,
        png::ColorType::Grayscale => 1,
        png::ColorType::GrayscaleAlpha => 2,
        png::ColorType::Indexed => return Err("PNG palette did not expand".into()),
    };
    let mut rgb = Vec::with_capacity((w as usize) * (h as usize) * 3);
    for px in buf[..info.buffer_size()].chunks_exact(channels) {
        match channels {
            1 => rgb.extend_from_slice(&[px[0], px[0], px[0]]),
            2 => rgb.extend_from_slice(&[px[0], px[0], px[0]]),
            3 => rgb.extend_from_slice(&px[..3]),
            _ => rgb.extend_from_slice(&px[..3]),
        }
    }
    Ok((rgb, w, h))
}

/// Build the standard source container plus its gain-map descriptor for an
/// input that carries no ProXDR gain map, so the regular UHDR conversion path
/// runs unchanged. The gain map is an identity (no boost) so an SDR source is
/// not promoted to HDR.
pub fn synthesize_sdr_source(data: &[u8]) -> Result<(Vec<u8>, ExtractedLhdr), String> {
    let (mut rgb, mut w, mut h, oriented) = decode_to_rgb(data)?;

    // Exif is read independently of Ultra HDR support: a vendor JPEG with an
    // MPF but no hdrgm still carries the capture metadata.
    let mut exif_tiff = if data.starts_with(&[0xFF, 0xD8]) {
        uhdr_jpeg::extract_exif_tiff(data)
    } else {
        styles_attach::extract_exif_tiff(data)
    }
    .map(|t| styles_attach::strip_note_from_tiff(&t));

    if !oriented {
        // jpeg-decoder hands back the stored (capture) orientation; put the
        // pixels into presentation orientation before storing them, and stop
        // declaring a rotation in the Exif below.
        let orientation = exif_tiff
            .as_deref()
            .map(exif::parse_exif_orientation)
            .transpose()?
            .unwrap_or(exif::ExifOrientation::Normal);
        let (rotated, rw, rh) = crate::isobmff_write::orient_gainmap_pixels(
            &rgb,
            w,
            h,
            3,
            w as usize * 3,
            orientation,
        )
        .map_err(|e| format!("SDR source orientation: {e}"))?;
        rgb = rotated;
        w = rw;
        h = rh;
    }
    // The stored pixels are in presentation orientation either way.
    if let Some(tiff) = exif_tiff.as_mut() {
        exif::normalize_tiff_orientation(tiff);
    }

    let container =
        uhdr_jpeg::synthesize_source_container_from_rgb(&rgb, w, h, exif_tiff, true)?;
    let extracted = ExtractedLhdr {
        mode: "uhdr".into(),
        meta_bytes: Vec::new(),
        meta_floats: uhdr_jpeg::neutral_meta_floats(),
        mask_data: None,
        gainmap_data: Some(uhdr_jpeg::IDENTITY_GAINMAP_JPEG.to_vec()),
        manifest_entries: None,
    };
    Ok((container, extracted))
}
